Purrsock: src/internal.h File Reference
internal.h File Reference
#include "purrsock/purrsock.h"
Data Structures
struct _purrsock_socket_t
Functions
bool _purrsock_init ()
void _purrsock_cleanup ()
ps_result_t _purrsock_create_socket (_purrsock_socket_t *socket)
ps_result_t _purrsock_create_socket_from_addr (_purrsock_socket_t *socket, const char *ip, ps_port_t port)
void _purrsock_destroy_socket (_purrsock_socket_t *socket)
ps_result_t _purrsock_bind_socket (_purrsock_socket_t *socket, const char *ip, ps_port_t port)
ps_result_t _purrsock_listen_socket (_purrsock_socket_t *socket)
ps_result_t _purrsock_accept_socket (_purrsock_socket_t *socket, _purrsock_socket_t **client)
ps_result_t _purrsock_connect_socket (_purrsock_socket_t *socket, const char *ip, ps_port_t port)
ps_result_t _purrsock_read_socket_packet (_purrsock_socket_t *socket, ps_packet_t *packet, _purrsock_socket_t **from)
ps_result_t _purrsock_send_socket_packet (_purrsock_socket_t *socket, ps_packet_t packet, _purrsock_socket_t *to)
Function Documentation
_purrsock_accept_socket()
ps_result_t _purrsock_accept_socket (_purrsock_socket_t * socket, _purrsock_socket_t ** client)
Referenced by ps_accept_socket().
_purrsock_bind_socket()
ps_result_t _purrsock_bind_socket (_purrsock_socket_t * socket, const char * ip, ps_port_t port)
Referenced by ps_bind_socket().
_purrsock_cleanup()
void _purrsock_cleanup ()
Referenced by ps_cleanup().
_purrsock_connect_socket()
ps_result_t _purrsock_connect_socket (_purrsock_socket_t * socket, const char * ip, ps_port_t port)
Referenced by ps_connect_socket().
_purrsock_create_socket()
ps_result_t _purrsock_create_socket (_purrsock_socket_t * socket)
Referenced by ps_create_socket().
_purrsock_create_socket_from_addr()
ps_result_t _purrsock_create_socket_from_addr (_purrsock_socket_t * socket, const char * ip, ps_port_t port)
Referenced by ps_create_socket_from_addr().
_purrsock_destroy_socket()
void _purrsock_destroy_socket (_purrsock_socket_t * socket)
Referenced by ps_destroy_socket().
_purrsock_init()
bool _purrsock_init ()
Referenced by ps_init().
_purrsock_listen_socket()
ps_result_t _purrsock_listen_socket (_purrsock_socket_t * socket)
Referenced by ps_listen_socket().
_purrsock_read_socket_packet()
ps_result_t _purrsock_read_socket_packet (_purrsock_socket_t * socket, ps_packet_t * packet, _purrsock_socket_t ** from)
Referenced by ps_read_socket_packet().
_purrsock_send_socket_packet()
ps_result_t _purrsock_send_socket_packet (_purrsock_socket_t * socket, ps_packet_t packet, _purrsock_socket_t * to)
Referenced by ps_send_socket_packet().