Purrsock: src/purrsock.c File Reference
purrsock.c File Reference
#include "internal.h"
#include <stdlib.h>
#include <assert.h>
Functions
const char * ps_result_to_cstr (ps_result_t result)
Converts a ps_result_t result code to a human-readable string.
bool ps_init ()
Initializes the socket library.
void ps_cleanup ()
Cleans up the socket library.
ps_result_t ps_create_socket (ps_socket_t *socket, ps_protocol_t protocol)
Creates a socket of the specified protocol.
ps_result_t ps_create_socket_from_addr (ps_socket_t *socket, ps_protocol_t protocol, const char *ip, ps_port_t port)
Creates a socket from an address and port.
void ps_destroy_socket (ps_socket_t socket)
Destroys a socket, releasing its resources.
ps_result_t ps_bind_socket (ps_socket_t socket, const char *ip, ps_port_t port)
Binds a socket to a specific IP address and port.
ps_result_t ps_listen_socket (ps_socket_t socket)
Puts the socket into listening mode, waiting for incoming connections.
ps_result_t ps_accept_socket (ps_socket_t socket, ps_socket_t *client)
Accepts an incoming connection on a listening socket.
ps_result_t ps_connect_socket (ps_socket_t socket, const char *ip, ps_port_t port)
Connects a socket to a remote server.
ps_result_t ps_read_socket_packet (ps_socket_t socket, ps_packet_t *packet, ps_socket_t *from)
Reads a packet of data from a socket.
ps_result_t ps_send_socket_packet (ps_socket_t socket, ps_packet_t packet, ps_socket_t to)
Sends a packet of data through a socket.
Function Documentation
ps_accept_socket()
ps_result_t ps_accept_socket (ps_socket_t socket, ps_socket_t * client)
Accepts an incoming connection on a listening socket.
Parameters
socket The listening socket.
client Pointer to a variable that will hold the accepted client socket.
Returns
A ps_result_t result code indicating the success or failure of the operation.
Definition at line 77 of file purrsock.c.
{
  return _purrsock_accept_socket((_purrsock_socket_t*)socket, (_purrsock_socket_t**)client);
}
References _purrsock_accept_socket().
ps_bind_socket()
ps_result_t ps_bind_socket (ps_socket_t socket, const char * ip, ps_port_t port)
Binds a socket to a specific IP address and port.
Parameters
socket The socket to bind.
ip The IP address to bind to.
port The port to bind to.
Returns
A ps_result_t result code indicating the success or failure of the operation.
Definition at line 69 of file purrsock.c.
{
  return _purrsock_bind_socket((_purrsock_socket_t*)socket, ip, port);
}
References _purrsock_bind_socket().
ps_cleanup()
void ps_cleanup ()
Cleans up the socket library.
This function must be called to clean up resources after using socket operations.
Definition at line 39 of file purrsock.c.
                  {
  _purrsock_cleanup();
}
References _purrsock_cleanup().
ps_connect_socket()
ps_result_t ps_connect_socket (ps_socket_t socket, const char * ip, ps_port_t port)
Connects a socket to a remote server.
Parameters
socket The socket to connect.
ip The IP address of the remote server.
port The port of the remote server.
Returns
A ps_result_t result code indicating the success or failure of the operation.
Definition at line 81 of file purrsock.c.
{
  return _purrsock_connect_socket((_purrsock_socket_t*)socket, ip, port);
}
References _purrsock_connect_socket().
ps_create_socket()
ps_result_t ps_create_socket (ps_socket_t * socket, ps_protocol_t protocol)
Creates a socket of the specified protocol.
Parameters
socket Pointer to a variable that will hold the created socket.
protocol The protocol to use for the socket (TCP or UDP).
Returns
A ps_result_t result code indicating the success or failure of the operation.
Definition at line 43 of file purrsock.c.
{
  assert(socket);
  _purrsock_socket_t *internal_socket = (_purrsock_socket_t*)malloc(sizeof(*internal_socket));
  assert(internal_socket);
  internal_socket->protocol = protocol;
  *socket = (ps_socket_t)internal_socket;
  return _purrsock_create_socket(internal_socket);
}
References _purrsock_create_socket(), and _purrsock_socket_t::protocol.
ps_create_socket_from_addr()
ps_result_t ps_create_socket_from_addr (ps_socket_t * socket, ps_protocol_t protocol, const char * ip, ps_port_t port)
Creates a socket from an address and port.
Parameters
socket Pointer to a variable that will hold the created socket.
protocol The protocol to use for the socket (TCP or UDP).
ip The IP address to bind the socket to.
port The port to bind the socket to.
Returns
A ps_result_t result code indicating the success or failure of the operation.
Definition at line 53 of file purrsock.c.
{
  assert(socket);
  _purrsock_socket_t *internal_socket = (_purrsock_socket_t*)malloc(sizeof(*internal_socket));
  assert(internal_socket);
  internal_socket->protocol = protocol;
  *socket = (ps_socket_t)internal_socket;
  return _purrsock_create_socket_from_addr(internal_socket, ip, port);
}
References _purrsock_create_socket_from_addr(), and _purrsock_socket_t::protocol.
ps_destroy_socket()
void ps_destroy_socket (ps_socket_t socket)
Destroys a socket, releasing its resources.
Parameters
socket The socket to destroy.
Definition at line 63 of file purrsock.c.
{
  assert(socket);
  _purrsock_destroy_socket((_purrsock_socket_t*)socket);
  free(socket);
}
References _purrsock_destroy_socket().
ps_init()
bool ps_init ()
Initializes the socket library.
This function must be called before using any socket operations.
Returns
true if initialization is successful, false otherwise.
Definition at line 35 of file purrsock.c.
               {
  return _purrsock_init();
}
References _purrsock_init().
ps_listen_socket()
ps_result_t ps_listen_socket (ps_socket_t socket)
Puts the socket into listening mode, waiting for incoming connections.
Parameters
socket The socket to listen on.
Returns
A ps_result_t result code indicating the success or failure of the operation.
Definition at line 73 of file purrsock.c.
{
  return _purrsock_listen_socket((_purrsock_socket_t*)socket);
}
References _purrsock_listen_socket().
ps_read_socket_packet()
ps_result_t ps_read_socket_packet (ps_socket_t socket, ps_packet_t * packet, ps_socket_t * from)
Reads a packet of data from a socket.
Parameters
socket The socket to read data from.
packet Pointer to a ps_packet_t structure to hold the read data.
from Pointer to a ps_socket_t variable to hold the sender's socket (optional).
Returns
A ps_result_t result code indicating the success or failure of the operation.
Definition at line 85 of file purrsock.c.
{
  return _purrsock_read_socket_packet((_purrsock_socket_t*)socket, packet, (_purrsock_socket_t**)from);
}
References _purrsock_read_socket_packet().
ps_result_to_cstr()
const char * ps_result_to_cstr (ps_result_t result)
Converts a ps_result_t result code to a human-readable string.
Parameters
result The result code to convert.
Returns
A string representation of the result code.
Definition at line 14 of file purrsock.c.
{
  switch (result) {
  case PS_CONNCLOSED:         return "Connection closed";
  case PS_ERROR_INTERNAL:     return "Internal error";
  case PS_SUCCESS:            return "Success";
  case PS_ERROR_NOTINIT:      return "Error not initialized";
  case PS_ERROR_MSGTOOLONG:   return "Error msg too long";
  case PS_ERROR_ADDRINUSE:    return "Error addr in use";
  case PS_ERROR_ADDRNOTAVAIL: return "Error addr not avail";
  case PS_ERROR_NETDOWN:      return "Error net down";
  case PS_ERROR_NETRESET:     return "Error net reset";
  case PS_ERROR_CONNRESET:    return "Error conn reset";
  case PS_ERROR_CONNREFUSED:  return "Error conn refused";
  case PS_ERROR_HOSTDOWN:     return "Error host down";
  case PS_ERROR_SHUTDOWN:     return "Error shut down";
  case PS_ERROR_UNKNOWN:      return "Unknown error";
  }
  assert(0 && "Unreachable");
  return NULL;
}
References PS_CONNCLOSED, PS_ERROR_ADDRINUSE, PS_ERROR_ADDRNOTAVAIL, PS_ERROR_CONNREFUSED, PS_ERROR_CONNRESET, PS_ERROR_HOSTDOWN, PS_ERROR_INTERNAL, PS_ERROR_MSGTOOLONG, PS_ERROR_NETDOWN, PS_ERROR_NETRESET, PS_ERROR_NOTINIT, PS_ERROR_SHUTDOWN, PS_ERROR_UNKNOWN, and PS_SUCCESS.
ps_send_socket_packet()
ps_result_t ps_send_socket_packet (ps_socket_t socket, ps_packet_t packet, ps_socket_t to)
Sends a packet of data through a socket.
Parameters
socket The socket to send data through.
packet The packet of data to send.
to The socket to send the data to.
Returns
A ps_result_t result code indicating the success or failure of the operation.
Definition at line 89 of file purrsock.c.
{
  return _purrsock_send_socket_packet((_purrsock_socket_t*)socket, packet, (_purrsock_socket_t*)to);
}
References _purrsock_send_socket_packet().